name: Azure Function To Deploy

on: 
  push:
    branches:
      - master

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'

jobs:
  build:
    runs-on: ubuntu-latest
    # 複数のバージョンを指定
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
    
    steps:
      - uses: actions/checkout@v3
      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64' 

      - name: 'azure function用にpip install'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd
     
      - name: Test with pytest
        run: |
          pytest
  