name: Azure Function To Deploy

on: 
  push:
    branches:
      - master

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  AZURE_FUNCTIONAPP_NAME: sample-python-githubactions
  PYTHON_VERSION: '3.9'

jobs:
  build:
    runs-on: ubuntu-latest
    # 複数のバージョンを指定
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9"]
    
    steps:
      - uses: actions/checkout@v3
      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64' 

      - name: 'azure function用にpip install'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd
     
      - name: Test with pytest
        run: |
          pytest


  deploy:
    - name: build job is succesed
    if: ${{success()}}
    needs: [build]
    
    runs-on: ubuntu-latest
    steps:
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
    