name: Azure Function Deploy

on:
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  AZURE_FUNCTIONAPP_NAME: sample-python-githubactions
  PYTHON_VERSION: '3.9'


jobs:
  deploy_from_base:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: ./.github/workflows/base

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}