name: Deploy To Azure Function


on: 
  # 手動でデプロイする
  workflow_dispatch:
    inputs:
      ref:
        description: branch|tag|SHA to checkout
        default: 'master'
        required: true

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  AZURE_FUNCTIONAPP_NAME: sample-python-githubactions # Azure Functionの名前を入力
  PYTHON_VERSION: '3.9'


jobs:
  deploy_from_base:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3
      with:
          ref: ${{ github.event.inputs.ref }}
          
      - name: call base workflow
      - uses: ./.github/workflows/base
      
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}