name: Deploy To Azure Function


on: 
  workflow_dispatch:
    inputs:
      ref:
        description: branch|tag|SHA to checkout
        default: 'master'
        required: true

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  AZURE_FUNCTIONAPP_NAME: etj-function # Azure Functionの名前を入力
  PYTHON_VERSION: '3.9'


jobs:
  callbaseworkflow:
    uses: ./.github/workflows/base.yml
  deploy_from_base:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}